services:
  recording:
    build:
      context: ./recording
      target: dev
    working_dir: /app
    command: sh -c "mkdir -p /app/storage/recordings /app/storage/recordings/encoded && npm run start:dev"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./recording:/app
      - recording_node_modules:/app/node_modules
      - ./storage:/app/storage

  encoder:
    build:
      context: ./encoder
      target: dev
    working_dir: /app
    command: sh -c "mkdir -p /app/storage/recordings/encoded && npm run start:dev"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./encoder:/app
      - encoder_node_modules:/app/node_modules
      - ./storage:/app/storage

  gateway:
    build:
      context: ./gateway
      target: dev
    working_dir: /app
    command: npm run start:dev
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./gateway:/app
      - gateway_node_modules:/app/node_modules

  video-metadata-service:
    build:
      context: ./video-metadata-service
      target: dev
    working_dir: /app
    command: ./mvnw spring-boot:run
    environment:
      SPRING_DEVTOOLS_RESTART_ENABLED: "true"
    volumes:
      - ./video-metadata-service:/app
      - video_metadata_m2:/root/.m2

volumes:
  recording_node_modules:
  encoder_node_modules:
  gateway_node_modules:
  video_metadata_m2:
