name: Build and archive a node
run-name:  Build ${{fromJson(vars.SERVICES)}} service  by @${{github.actor}}

on:
  pull_request_target:
      branches: [main,develop]

  
jobs:
    build-and-archive:
        name: Build ${{matrix.service}}
        runs-on: ubuntu-latest
        
        strategy:
            fail-fast: false
            matrix:
                node-version: ${{fromJson(vars.NODE_VERSIONS)}}
                service: ${{fromJson(vars.SERVICES)}}

        defaults:
            run:
                working-directory: ./${{matrix.service}}
        steps: 
        -   name: Checkout repository
            uses: actions/checkout@v4
            with:
                ref: ${{github.event.pull_request.head.sha}}


        -   name: Setup Node.js@v${{ matrix.node-version }} environment 
            uses: actions/setup-node@v4
            with:
                node-version: ${{ matrix.node-version }}
            
        -   name: Install dependencies
            run: npm ci
        
        -   name: Install FFMPEG
            if: matrix.service == 'recording'||matrix.service == 'encoder'
            run: sudo apt-get update && sudo apt-get install -y ffmpeg 

        -   name: Build ${{matrix.service}}
            run: npm run build

        -   name: Upload a Build Artifact
            uses: actions/upload-artifact@v4
            with:
                name: ${{matrix.service}}-${{matrix.node-version}}@v${{github.run_id}}
                path: .
