name: Run unit test
run-name: Run unit tests for the ${{fromJson(vars.SERVICES)}} service by @${{github.actor}}
on:
  workflow_run: 
    branches: develop
    types: completed
    workflows: Build and archive a node ##Workflow might not run if the name of source worflow changes
  
jobs:  
  run-unit-test:
    name: Run ${{matrix.service}} unit test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: ${{fromJson(vars.NODE_VERSIONS)}}
        service: ${{fromJson(vars.SERVICES)}}

    defaults:
      run:
        working-directory: ./${{matrix.service}}
    if: ${{github.event.workflow_run.conclusion == 'success'}}
    steps:

    - name: Setup Node.js@v${{ matrix.node-version }} environment 
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Download a Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{matrix.service}}-${{matrix.node-version}}@v${{github.event.workflow_run.id}}
        path: .
        
    - name: Run unit tests
      run: npm test

    
    
    
    
    
