name: Increase the number of VERSION_BOTTOM
  
on:
  pull_request:
    branches: [main,develop]

jobs:
  update-count-of-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Increase and update the bottom number of version
        run: |
          $count=${{vars.VERSION_BOTTOM}}
          gh variable set PULL_REQUEST_COUNT $(count+1)

        
          
        
